### PR TITLE
Reference dumper

### LINKED ISSUE #25: dump gadget config reference
a cli command to dump gadget config references

### PR DESCRIPTION
**Pull request by DavidBadura**
add a new command to dump config reference

```bash
# dump for all gadgets
bin/simpspector reference

# dump for 'comment_blacklist' gadget
bin/simpspector reference comment_blacklist
```

output:

```yaml
comment_blacklist:
    files:

        # Default:
        - ./
    blacklist:

        # Defaults:
        todo:                notice
        dont commit:         error
```

fixes #25

### CODE REVIEW

**Comment by dragonito** [comment]
+1

**Comment by DavidBadura** [comment]
change command name from `dump-config-reference` to `reference`

**Comment by tolry** [comment]
:+1: 

no time to review - we can refactor everything on the hackday anyway :smile:

**Comment by DavidBadura** [comment]
we have two :+1: :wink:

**Pull request merged**
