### PR TITLE
Change copyright

### PR DESCRIPTION
**Pull request by dragonito**
Lets just add "Simpspector" instead of "SimpleThings GmbH"

### CODE REVIEW

**Comment by DavidBadura** [comment]
"SimpSpector" pls :wink:

**Comment by DavidBadura** [comment]
fix #48

**Comment by dragonito** [comment]
;) +1

**Comment by tolry** [comment]
@dragonito so will you fix tihs?

**Comment by dragonito** [comment]
Done

**Comment by tolry** [comment]
Thx!

**Comment by DavidBadura** [comment]
@dragonito next issue? :wink: https://github.com/simpspector/simpspector/issues/111

**Pull request merged**
